#!/bin/bash
echo "Regenerating host keys"
KEYS="rsa dsa ecdsa"

for KEY in $KEYS
do
  rm -f /etc/ssh/ssh_host_${KEY}_key
  ssh-keygen -f /etc/ssh/ssh_host_${KEY}_key -N '' -t $KEY
done

echo "Cleaning up"
rm /etc/init.d/template_bootstrap
reboot
